### ISSUE TITLE
[ENH]: Add aliases for k8s

### ISSUE THREAD

**Issue by akshayvadher** [2KAbhishek/dots2k#20]
### Description

k8s is common item that is accessed using cli. `kubectl` is the way to go, but it is very long. It is common to have kubectl installed on dev's machine. 

### Additional Information

Common things I use are

`k` for `kubectl`
`po` for `k get po`
`poa` = `k get po -A`
`ka` = `k get all`
`kl` = `k logs -f`

**Comment by 2KAbhishek** [comment]
The `kubectl` oh-my-zsh plugin adds a bunch of k8s aliases, you can enable it by adding it to the `plugins` list in your `~/.zshrc` file

Here's the [link to the plugin README](https://github.com/ohmyzsh/ohmyzsh/blob/4fd2af0a82e2826317d9551ecd8d5f44553828d7/plugins/kubectl/README.md)
